apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: service-config
  labels:
    app: service-config
spec:
  type: NodePort
  ports:
  - port: 80
    name: service-config
    targetPort: 8080
  selector:
    app: service-config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-config
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: service-config
    spec:
      containers:
      - name: service-config
        image: mitraisosc/com.mitrais.microservices-configuration-service:0.0.0-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
        - name: EUREKA_URI
          value: http://service-registry/eureka